# Generated by Django 2.1.5 on 2019-02-22 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AVs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avast', models.CharField(max_length=200, null=True)),
                ('bitdefender', models.CharField(max_length=200, null=True)),
                ('drweb', models.CharField(max_length=200, null=True)),
                ('emsisoft', models.CharField(max_length=200, null=True)),
                ('eset', models.CharField(max_length=200, null=True)),
                ('kasp', models.CharField(max_length=200, null=True)),
                ('symantec', models.CharField(max_length=200, null=True)),
                ('malwarebytes', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mitre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attack_id', models.CharField(max_length=200, null=True)),
                ('tactic', models.CharField(max_length=200, null=True)),
                ('technique', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=200, null=True)),
                ('domain', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NoHA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sha256', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Ransomwares',
            fields=[
                ('ransom_name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('parent', models.CharField(max_length=200, null=True)),
                ('family', models.CharField(max_length=200, null=True)),
                ('similar', models.CharField(max_length=200, null=True)),
                ('isroot', models.BooleanField(max_length=200, null=True)),
                ('attacktype', models.CharField(max_length=200, null=True)),
                ('author', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Samples',
            fields=[
                ('sample', models.IntegerField(primary_key=True, serialize=False)),
                ('sha256', models.CharField(max_length=200)),
                ('extension', models.CharField(max_length=200, null=True)),
                ('wallettype', models.CharField(max_length=200, null=True)),
                ('walletno', models.CharField(max_length=200, null=True)),
                ('mutex', models.CharField(max_length=200, null=True)),
                ('publickey', models.CharField(max_length=200, null=True)),
                ('encryption', models.CharField(max_length=200, null=True)),
                ('deckey', models.CharField(max_length=200, null=True)),
                ('imphash', models.CharField(max_length=200, null=True)),
                ('ssdeep', models.CharField(max_length=200, null=True)),
                ('authentihash', models.CharField(max_length=200, null=True)),
                ('ransom_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ransomware.Ransomwares')),
            ],
        ),
        migrations.CreateModel(
            name='Sections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sec_name', models.CharField(max_length=20, null=True)),
                ('sec_hash', models.CharField(max_length=32, null=True)),
                ('sample_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ransomware.Samples')),
            ],
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200, null=True)),
                ('social_id', models.CharField(max_length=200, null=True)),
                ('platform', models.CharField(max_length=200, null=True)),
                ('sample_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ransomware.Samples')),
            ],
        ),
        migrations.CreateModel(
            name='Times',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compiletime', models.CharField(max_length=10)),
                ('firstsubmisison', models.CharField(max_length=10)),
                ('sample_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ransomware.Samples')),
            ],
        ),
        migrations.AddField(
            model_name='noha',
            name='sample_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ransomware.Samples'),
        ),
        migrations.AddField(
            model_name='network',
            name='sample_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ransomware.Samples'),
        ),
        migrations.AddField(
            model_name='mitre',
            name='sample_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ransomware.Samples'),
        ),
        migrations.AddField(
            model_name='avs',
            name='sample_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ransomware.Samples'),
        ),
    ]
